### PR TITLE
Fixes rancher-sandbox/baremetal#17

### PR DESCRIPTION
**Pull request by mfatrez**
Signed-off-by: Matthieu Fatrez <matthieu.fatrez@suse.com>

### CODE REVIEW

**Comment by guangyee** [comment]
>

**Comment by guangyee** [comment]
Sorry I clicked on the wrong button. Meant to reply to Tim's comment. This patch is using the RANCHER_VERSION and RANCHER_HOSTNAME from the env, which is set by script.sh and can be overwritten by explicitly setting the environments just like other component versions. This patch is not breaking from that pattern so we should be fine here.

**Review by guangyee — APPROVED** [review]
Looks good to me.

**Comment by timirnich** [comment]
Currently `render-templates.sh` is run independently and doesn't get called by `script.sh`. So the vars set in the deploy script are not available when the templates are rendered. The typical way of using the scripts is that `render-templates.sh` is run once when the repo gets checked out, and only gets re-run if something changes. 

Conceptually, the original idea was to use the gomplates for lab specific configuration, and do all other configuration that's not lab specific directly in script.sh. We've already deviated a bit from that, but I'd rather like to avoid going further in that direction to keep things simple.

**Pull request closed without merging**
